/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GradleDemoProject;

import static org.testng.Assert.assertTrue;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.Test;

public class LibraryTest {
	@Test
	public void testSomeLibraryMethod() {
		
		System.setProperty("webdriver.chrome.driver","C:/Users/deepa/Downloads/Browser Drivers/Chrome Drivers/chromedriver.exe" );
		WebDriver driver = new ChromeDriver();
		driver.quit();
		Library classUnderTest = new Library();
		assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
	}
}